#!/usr/bin/env php
<?php

use PhpSlides\Console;

shell_exec('composer dump-autoload');

// Register the Composer autoloader...
require_once __DIR__ . '/vendor/autoload.php';

// Handle all console commands...
(new Console($argv))
   ->listen(host: 'localhost', port: 2200)
   ->resolve(__DIR__)
   ->debug(true);