#!/usr/bin/env php
<?php

use PhpSlides\Console\Console;

shell_exec('composer dump-autoload');

// Register the Composer autoloader...
require_once __DIR__.'/vendor/autoload.php';

// Bootstrap PhpSlides and handle the command...
$output = (new Console($argv))->output();
exit($output);